### ISSUE TITLE
Unnecessary config can cause problems

### ISSUE THREAD

**Issue by szerintem** [SzuniSOFT/laravel-szamlazzhu#4]
client.certificate.enabled is **false** but validation **fails** if client.certificate.path exists

config

> 'certificate' => [
             'enabled' => false,
             'disk' => 'local',
             'path' => 'szamlazzhu/cacert.pem'
        ]

validation error:

> InvalidClientConfigurationException
The specified cert file could not be resolved from disk [local] at path [szamlazzhu/cacert.pem]!

Also the exception did not contained the validation message.

**Comment by sykorax** [comment]
@dunaicapa thank you.

Will fix it during the next week.

**Comment by sykorax** [comment]
Fixed at [https://github.com/SzuniSOFT/laravel-szamlazzhu/commit/a3b4754a7b1e6234cd04f9109a4adf159ce41185](https://github.com/SzuniSOFT/laravel-szamlazzhu/commit/a3b4754a7b1e6234cd04f9109a4adf159ce41185)

Please reopen if the issue persists.

**Comment by IllesAprod** [comment]
@sykorax This problem still occurs for me. using v1.2.1, laravel 5.8.

Are you open for pull requests? I would like to improve exception messages too, now only throws the exceptions but not showing the current message.

**Comment by sykorax** [comment]
Hey @IllesAprod

Sure. PRs are welcomed always.

> @sykorax This problem still occurs for me. using v1.2.1, laravel 5.8.

I'll have a look at this the next week.

> I would like to improve exception messages too, now only throws the exceptions but not showing the current message.

What kind of exception messages are you missing?

**Comment by IllesAprod** [comment]
When I running invoce creation in tinker (php artisan tinker) only Exception names shown, not the whole exception message, and it was hard to debug 4-5 problems without the exact messages.

**Comment by sykorax** [comment]
@IllesAprod 
I don't know much about Tinker. Can you please share an example?
(I mean like expected vs. actual)

Also please tell which exception raised with no message.

**Comment by nxu** [comment]
I've sent in a PR with the fix in it. There's a semantic error in the validation, there's an unnecessary `file_exists` call inside the `Storage::exists()` method call.
